site_name: Grego
site_url: https://moronbandin.github.io/grego
theme:
  name: material
  language: gl
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.highlight
    - search.suggest

plugins:
  - search

nav:
  - Inicio: index.md
  -  Unidades:
      - Primeiro Trimestre (1AV): 
          - Unidade 1:
              -  Introduci贸n: UNIDADES/1AV/1/index.md
              -  Texto en Markdown: UNIDADES/1AV/1/textos/1.md
              -  Teor铆a: UNIDADES/1AV/1/teoria/apuntes.md
          - Unidade 2:
              -  Introduci贸n: UNIDADES/1AV/2/index.md
              -  Texto en Markdown: UNIDADES/1AV/2/textos/2.md
              -  Teor铆a: UNIDADES/1AV/2/teoria/apuntes.md
          - Unidade 3:
              -  Introduci贸n: UNIDADES/1AV/3/index.md
              -  Texto en Markdown: UNIDADES/1AV/3/textos/3.md
              -  Teor铆a: UNIDADES/1AV/3/teoria/apuntes.md
          - Unidade 4:
              -  Introduci贸n: UNIDADES/1AV/4/index.md
              -  Texto en Markdown: UNIDADES/1AV/4/textos/4.md
              -  Teor铆a: UNIDADES/1AV/4/teoria/apuntes.md
          - Unidade 5:
              -  Introduci贸n: UNIDADES/1AV/5/index.md
              -  Texto en Markdown: UNIDADES/1AV/5/textos/5.md
              -  Teor铆a: UNIDADES/1AV/5/teoria/apuntes.md
      - Segundo Trimestre (2AV): 
          - Unidade 6:
              -  Introduci贸n: UNIDADES/2AV/6/index.md
              -  Texto en Markdown: UNIDADES/2AV/6/textos/6.md
              -  Teor铆a: UNIDADES/2AV/6/teoria/apuntes.md
          - Unidade 7:
              -  Introduci贸n: UNIDADES/2AV/7/index.md
              -  Texto en Markdown: UNIDADES/2AV/7/textos/7.md
              -  Teor铆a: UNIDADES/2AV/7/teoria/apuntes.md
          - Unidade 8:
              -  Introduci贸n: UNIDADES/2AV/8/index.md
              -  Texto en Markdown: UNIDADES/2AV/8/textos/8.md
              -  Teor铆a: UNIDADES/2AV/8/teoria/apuntes.md
          - Unidade 9:
              -  Introduci贸n: UNIDADES/2AV/9/index.md
              -  Texto en Markdown: UNIDADES/2AV/9/textos/9.md
              -  Teor铆a: UNIDADES/2AV/9/teoria/apuntes.md
          - Unidade 10:
              -  Introduci贸n: UNIDADES/2AV/10/index.md
              -  Texto en Markdown: UNIDADES/2AV/10/textos/10.md
              -  Teor铆a: UNIDADES/2AV/10/teoria/apuntes.md
      - Terceiro Trimestre (3AV):
          - Unidade 11:
              -  Introduci贸n: UNIDADES/3AV/11/index.md
              -  Texto en Markdown: UNIDADES/3AV/11/textos/11.md
              -  Teor铆a: UNIDADES/3AV/11/teoria/apuntes.md
          - Unidade 12:
              -  Introduci贸n: UNIDADES/3AV/12/index.md
              -  Texto en Markdown: UNIDADES/3AV/12/textos/12.md
              -  Teor铆a: UNIDADES/3AV/12/teoria/apuntes.md
          - Unidade 13:
              -  Introduci贸n: UNIDADES/3AV/13/index.md
              -  Texto en Markdown: UNIDADES/3AV/13/textos/13.md
              -  Teor铆a: UNIDADES/3AV/13/teoria/apuntes.md
          - Unidade 14:
              -  Introduci贸n: UNIDADES/3AV/14/index.md
              -  Texto en Markdown: UNIDADES/3AV/14/textos/14.md
              -  Teor铆a: UNIDADES/3AV/14/teoria/apuntes.md
          - Unidade 15:
              -  Introduci贸n: UNIDADES/3AV/15/index.md
              -  Texto en Markdown: UNIDADES/3AV/15/textos/15.md
              -  Teor铆a: UNIDADES/3AV/15/teoria/apuntes.md
  -  Material Extra: UNIDADES/EXTRA/index.md



plugins:
  - search

extra:
  navigation.indexes: false
